// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-c4YzxLBoo5E77SQbTC3VwzCPnSVVr84',
    appId: '1:642645442772:web:a52b3eb3d7923688417b41',
    messagingSenderId: '642645442772',
    projectId: 'student-management-app-1c249',
    authDomain: 'student-management-app-1c249.firebaseapp.com',
    storageBucket: 'student-management-app-1c249.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8UBGFY_4XO-RbrLnMtIgfG4W_QTy3N40',
    appId: '1:642645442772:android:569b8870941a8f21417b41',
    messagingSenderId: '642645442772',
    projectId: 'student-management-app-1c249',
    storageBucket: 'student-management-app-1c249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7SeYk_W-PbJz7mbg81IYbxexd9f3BqLo',
    appId: '1:642645442772:ios:1f4d78bad2687510417b41',
    messagingSenderId: '642645442772',
    projectId: 'student-management-app-1c249',
    storageBucket: 'student-management-app-1c249.firebasestorage.app',
    iosBundleId: 'com.example.khushi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7SeYk_W-PbJz7mbg81IYbxexd9f3BqLo',
    appId: '1:642645442772:ios:1f4d78bad2687510417b41',
    messagingSenderId: '642645442772',
    projectId: 'student-management-app-1c249',
    storageBucket: 'student-management-app-1c249.firebasestorage.app',
    iosBundleId: 'com.example.khushi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-c4YzxLBoo5E77SQbTC3VwzCPnSVVr84',
    appId: '1:642645442772:web:d6c3b795dfab68ba417b41',
    messagingSenderId: '642645442772',
    projectId: 'student-management-app-1c249',
    authDomain: 'student-management-app-1c249.firebaseapp.com',
    storageBucket: 'student-management-app-1c249.firebasestorage.app',
  );
}